Importar biblioteques

In [1]:
import pandas as pd
import numpy as np

Crear diccionari

In [2]:
celebdict={}

Afegir noms

In [3]:
celebdict['names']=['Eustaqui','Anselma','Protasi','Bonifacia','Anaclet']

Afegir edats

In [4]:
celebdict['age']=[67,51,32,69,35]

Afegir gènere

In [5]:
celebdict['gender']=['m','f','f','m','f']

Afegir professió

In [6]:
celebdict['occup']=['actor','everything','singer','actor','singer']

Crear dataframe a partir del diccionari

Un DataFrame de Pandas és una estructura de dades de dues dimensions, com una matriu de dues dimensions, o una taula amb files i columnes.

In [7]:
df = pd.DataFrame(celebdict)

Mostrar df

In [8]:
print(df)

       names  age gender       occup
0   Eustaqui   67      m       actor
1    Anselma   51      f  everything
2    Protasi   32      f      singer
3  Bonifacia   69      m       actor
4    Anaclet   35      f      singer

Canviar el tipus de dada de l'atribut edat

In [9]:
df['age'].dtype

dtype('int64')

Mostrar el tipus de dada dels atributs

In [10]:
df.dtypes

names     object
age        int64
gender    object
occup     object
dtype: object

Mostra els 5 primers registres

In [11]:
df.head()

       names  age gender       occup
0   Eustaqui   67      m       actor
1    Anselma   51      f  everything
2    Protasi   32      f      singer
3  Bonifacia   69      m       actor
4    Anaclet   35      f      singer

Mostra els 3 primers registres

In [12]:
df.head(3)

      names  age gender       occup
0  Eustaqui   67      m       actor
1   Anselma   51      f  everything
2   Protasi   32      f      singer

Mostra els 5 últims registres

In [13]:
df.tail()

       names  age gender       occup
0   Eustaqui   67      m       actor
1    Anselma   51      f  everything
2    Protasi   32      f      singer
3  Bonifacia   69      m       actor
4    Anaclet   35      f      singer

Mostra els 3 últims registres

In [14]:
df.tail(3)

       names  age gender   occup
2    Protasi   32      f  singer
3  Bonifacia   69      m   actor
4    Anaclet   35      f  singer

Retorna les dimensions (columnes i registres) del df

In [15]:
df.shape

(5, 4)

Retorna els atributs

In [16]:
df.columns.values

array(['names', 'age', 'gender', 'occup'], dtype=object)

Retorna estadístiques

In [17]:
df.describe()

             age
count   5.000000
mean   50.800000
std    17.297399
min    32.000000
25%    35.000000
50%    51.000000
75%    67.000000
max    69.000000

Retorna un resum del df

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   age     5 non-null      int64
 2   gender  5 non-null      object
 3   occup   5 non-null      object
dtypes: int64(1), object(3)
memory usage: 288.0+ bytes